# qb-port-sync configuration example

[qbittorrent]
base_url = "http://127.0.0.1:8080"
username = "admin"
# If password is blank, QB_PORT_SYNC_QB_PASSWORD will be used at runtime.
password = ""

[protonvpn]
# Linux default resolves to /run/user/$UID/Proton/VPN/forwarded_port when empty
forwarded_port_path = ""

[portmap]
internal_port = 0
protocol = "BOTH"
refresh_secs = 300
autodiscover_gateway = true
gateway = ""

[net]
# Optional interface binding for qBittorrent (e.g., "tun0", "utun5")
bind_interface = ""

[metrics]
# Enable Prometheus metrics endpoint at /metrics
enabled = false
port = 0  # Set to non-zero to enable (e.g., 9000)

[health]
# Enable health check endpoint at /healthz
enabled = false
port = 0  # Set to non-zero to enable, or 0 to use metrics port
